# DDPM config used for DDPM training
ddpm:
  data:
    root: /data/jupyter/DiffuseVAE/datasets/   # Dataset root
    name: "cifar10"   # Dataset name (check main/util.py `get_dataset` for a registry)
    image_size: 32   # Image resolution
    hflip: True   # Whether to use horizontal flip
    n_channels: 3   # Num input channels
    norm: True   # Whether to scale data between [-1, 1]

  model:   # UNet specific params. Check the DDPM implementation for details on these
    dim : 128
    attn_resolutions: "16,"
    n_residual: 2
    dim_mults: "1,2,2,2"
    dropout: 0.3
    n_heads: 8
    beta1: 0.0001
    beta2: 0.02
    n_timesteps: 1000
    enc_block_config : "32x7,32d2,32t16,16x4,16d2,16t8,8x4,8d2,8t4,4x3,4d4,4t1,1x3"
    enc_channel_config: "32:64,16:128,8:256,4:256,1:512"
    dec_block_config: "1x1,1u4,1t4,4x2,4u2,4t8,8x3,8u2,8t16,16x7,16u2,16t32,32x15"
    dec_channel_config: "32:64,16:128,8:256,4:256,1:512"


  training:
    seed: 0   # Random seed
    fp16: true   # Whether to use fp16
    use_ema: True   # Whether to use EMA (Improves sample quality)
    z_cond: False   # Whether to condition UNet on vae latent
    z_dim: 512   # Dimensionality of the vae latent
    type: 'form1'   # DiffuseVAE type. One of ['form1', 'form2', 'uncond']. `uncond` is baseline DDPM
    ema_decay: 0.9999   # EMA decay rate
    batch_size: 32   # Training batch size (per GPU, per TPU core if using distributed training)
    epochs: 500   # Max number of epochs
    log_step: 1   # log interval
    device: "gpu:0"   # Device. Uses TPU/CPU if set to `tpu` or `cpu`. For GPU, use gpu:<comma separated id list>. Ex: gpu:0,1 would run only on gpus 0 and 1 
    chkpt_interval: 1   # Number of epochs between two checkpoints
    optimizer: "Adam"   # Optimizer
    lr: 2e-4   # Learning rate
    restore_path: ""   # Checkpoint restore path
    vae_chkpt_path: ???   # VAE checkpoint path. Useful when using form1 or form2
    results_dir: ???   # Directory to store the checkpoint in
    workers: 4   # Num workers
    grad_clip: 1.0   # gradient clipping threshold
    n_anneal_steps: 5000   # number of warmup steps
    loss: "l2"   # Diffusion loss type. Among ['l2', 'l1']
    chkpt_prefix: ""   # prefix appended to the checkpoint name
    cfd_rate: 0.0   # Conditioning signal dropout rate as in Classifier-free guidance
    vae_weight: 1.0  # VAE 손실 가중치
    ddpm_weight: 1.0  # DDPM 손실 가중치
    anneal_start: 0  # Annealing 시작 에포크
    anneal_end: 100  # Annealing 종료 에포크
    flow_base_dim: 64          # RealNVP의 기본 차원 설정
    flow_res_blocks: 8         # Residual block 개수
    flow_bottleneck: true      # Bottleneck 사용 여부
    flow_skip: true            # Skip 연결 사용 여부
    flow_weight_norm: true     # Weight Normalization 사용 여부
    flow_coupling_bn: true     # Coupling 이후 BatchNorm 사용 여부
    flow_affine: true          # Affine Coupling 사용 여부
    alpha: 1.0

# VAE config used for VAE training
vae:
  data:
    root: "/data/jupyter/yeon/DiffuseVAE/datasets/"
    name: "cifar10"
    image_size: 32
    n_channels: 3
    hflip: False

  model:  # VAE specific params. Check the `main/models/vae.py`
    enc_block_config : "32x7,32d2,32t16,16x4,16d2,16t8,8x4,8d2,8t4,4x3,4d4,4t1,1x3"
    enc_channel_config: "32:64,16:128,8:256,4:256,1:512"
    dec_block_config: "1x1,1u4,1t4,4x2,4u2,4t8,8x3,8u2,8t16,16x7,16u2,16t32,32x15"
    dec_channel_config: "32:64,16:128,8:256,4:256,1:512"

  training:   # Most of these are same as explained above but for VAE training
    seed: 0
    fp16: False
    batch_size: 128
    epochs: 500
    log_step: 1
    device: "gpu:0"
    chkpt_interval: 1
    optimizer: "Adam"
    lr: 1e-4
    restore_path: ""
    results_dir: "/data/jupyter/yeon/DiffuseVAE/result"
    workers: 2
    chkpt_prefix: ""
    alpha: 1.0   # The beta value in beta-vae. I know the param name might be misleading :(
  